# This will be your default build command
[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.92.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# This will be your preview build
[context.deploy-preview]
command = "hugo --buildFuture --buildDrafts --gc --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.92.1"

# This will be your staging build
[context.staging]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.staging.environment]
HUGO_VERSION = "0.92.1"

